# List of Tor directory authorities and digests of their keys.
#
# Since Arti is currently client-only, there's no need to keep
# anything else about authorities (like addresses), since clients only
# connect to fallback directories.
#
# (List generated August 2020.)

[[network.authority]]
name = "moria1"
v3ident = "D586D18309DED4CD6D57C18FDB97EFA96D330566"

[[network.authority]]
name = "tor26"
v3ident = "14C131DFC5C6F93646BE72FA1401C02A8DF2E8B4"

[[network.authority]]
name = "dizum"
v3ident = "E8A9C45EDE6D711294FADF8E7951F4DE6CA56B58"

[[network.authority]]
name = "gabelmoo"
v3ident = "ED03BB616EB2F60BEC80151114BB25CEF515B226"

[[network.authority]]
name = "dannenberg"
v3ident = "0232AF901C31A04EE9848595AF9BB7620D4C5B2E"

[[network.authority]]
name = "maatuska"
v3ident = "49015F787433103580E3B66A1707A00E60F2D15B"

[[network.authority]]
name = "Faravahar"
v3ident = "EFCBE720AB3A82B99F9E953CD5BF50F7EEFC7B97"

[[network.authority]]
name = "longclaw"
v3ident = "23D15D965BC35114467363C165C4F724B64B4F66"

[[network.authority]]
name = "bastet"
v3ident = "27102BC123E7AF1D4741AE047E160C91ADC76B21"
