[package]
name = "tor-circmgr"
version = "0.0.0"
authors = ["Nick Mathewson <nickm@torproject.org>"]
edition = "2018"
license = "MIT OR Apache-2.0"
publish = false

[dependencies]
tor-chanmgr = { path="../tor-chanmgr", version= "*" }
tor-netdir = { path="../tor-netdir", version= "*" }
tor-netdoc = { path="../tor-netdoc", version= "*" }
tor-proto = { path="../tor-proto", version= "*" }
tor-linkspec = { path="../tor-linkspec", version= "*" }
tor-llcrypto = { path="../tor-llcrypto", version= "*" }
tor-rtcompat = { path="../tor-rtcompat", version= "*" }

anyhow = "1.0.35"
async-trait = "0.1.42"
event-listener = "2.5.1"
futures = "0.3.8"
rand = "0.7.3"
log = "0.4.11"
thiserror = "1.0.22"

[dev-dependencies]
futures-await-test = "0.3.0"
